app:
  api:
    url: http://localhost
    port: 8090
    
spring:
  devtools:
    livereload: 
      enabled : true
    restart: 
      enabled : true
  datasource:
    username: ENC(/XX7WM455CuBWLq8NAXntA==)
    password: ENC(2e7nPVOpdzcPNTn2/Lvu1/og8pVIUVyJ)
    url: ENC(5duuPPS8W36lVN9f63T6qlAmnsQYg8wDupjvxdi/WCC0IFV1uvVOLakAXLjcDrRtinycXU5tcaXlJaEnqH+0zgfXj9gr0SeNCXUtqUOjf7LrUaUrpJFjfs5hBR19q/1fomqm7F9orNo=)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jasypt:
  encryptor:
    bean: jasyptStringEncryptor