app:
  api:
    url: http://localhost
    port: 8090
spring:
  devtools:
    livereload: 
      enabled : true
    restart: 
      enabled : true
  datasource:
    username: ENC(058GvSA0fG9dLcgaG0QInw==)
    password: ENC(T91uIDM5OrUBtEyW2R7VCw==)
    url: ENC(2vRaebtX47xv+uhSyPBV+6L1sic/ivC505NRGVwWZs8fwBNlCWq6SzAQd2OfxLGJL7wq7Lny8IidzamD1EotnMPYP54Ty7wNdQ1hZnmayYWVMwqg7Unp6AgrYxnfhPpfU2qHU65U2aM=)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: