app:
  api:
    url: http://localhost
    port: 8090
spring:
  devtools:
    livereload: 
      enabled : true
    restart: 
      enabled : true
  datasource:
    username: ENC(V6atDWafbFXYnKSs3cugWQ==)
    password: ENC(tS9HZ5yynkm3zkXa69C/eg==)
    url: ENC(n31JYKWsmNglurbpvPgPqYW5RT1wQ2TlPpiCbNGLv9Fbi9wdmjjXaHOZrgTiQc41tn+1KiUjjBXle+jqhMsm4Atmkp4LJaTkL/jp0nE8cwqOuDJolKYuEe/ATvDa/v2HoJBx11wXmGI=)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor